### ISSUE TITLE
Method names without a space cause an error

### ISSUE THREAD

**Issue by leyshon** [danielpalme/OpenCoverToCoberturaConverter#11]
I've generated an OpenCover report using https://the.agilesql.club/blogs/Ed-Elliott/2016-04-08/SQLCover-Code-Coverage-For-SQL-Server-T-SQL this tool, running against the example tSQLt database. This gives me method names such as [Accelerator].[IsExperimentReady]. When I run OpenCoverToCoberturaConverter against this I get the below error. Having had a look this seems to relate to these lines in particular in the CreateMethodElement method.

                string methodreturn = methodreturnandclass.Split(' ')[0];
                string className = methodreturnandclass.Split(' ')[1];

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Palmmedia.OpenCoverToCoberturaConverter.Converter.CreateMethodElement(XElement module, XElement method, XElement classLinesElement, Int64& coveredLines, Int64& totalLines, In
t64& coveredBranches, Int64& totalBranches)
   at Palmmedia.OpenCoverToCoberturaConverter.Converter.CreateClassElement(String className, XElement module, Dictionary`2 filesById, Boolean includeGettersSetters, Int64& coveredL
ines, Int64& totalLines, Int64& coveredBranches, Int64& totalBranches, Regex commonPrefix)
   at Palmmedia.OpenCoverToCoberturaConverter.Converter.CreatePackageElement(XElement module, Boolean includeGettersSetters, Int64& coveredLines, Int64& totalLines, Int64& coveredB
ranches, Int64& totalBranches, Regex commonPrefix)
   at Palmmedia.OpenCoverToCoberturaConverter.Converter.CreatePackagesElement(XDocument openCoverReport, Boolean includeGettersSetters, Int64& coveredLines, Int64& totalLines, Int6
4& coveredBranches, Int64& totalBranches, Regex commonPrefix)
   at Palmmedia.OpenCoverToCoberturaConverter.Converter.CreateRootElement(XDocument openCoverReport, String sourcesDirectory, Boolean includeGettersSetters)
   at Palmmedia.OpenCoverToCoberturaConverter.Converter.ConvertToCobertura(XDocument openCoverReport, String sourcesDirectory, Boolean includeGettersSetters)
   at Palmmedia.OpenCoverToCoberturaConverter.Program.Main(String[] args)

**Comment by danielpalme** [comment]
Can you please upload the OpenCover report?

**Comment by leyshon** [comment]
I've had to change it to txt. In my own fork I've simply done the below to work around my particular use but I suspect this could cause problems in differently formatted OpenCover reports.

            string methodreturn;
            string className;

            if (methodreturnandclass.Contains(' '))
            {
                methodreturn = methodreturnandclass.Split(' ')[0];
                className = methodreturnandclass.Split(' ')[1];
            }
            else
            {
                methodreturn = methodreturnandclass.Split('.')[0];
                className = methodreturnandclass.Split('.')[1];
            }

[tsqlt_opencover.txt](https://github.com/danielpalme/OpenCoverToCoberturaConverter/files/767086/tsqlt_opencover.txt)

**Comment by danielpalme** [comment]
Included fix in this release:
https://www.nuget.org/packages/OpenCoverToCoberturaConverter/0.2.6
