### ISSUE TITLE
Unhandled exception in causes app to crash

### ISSUE THREAD

**Issue by asmagin** [danielpalme/OpenCoverToCoberturaConverter#21]
![image](https://user-images.githubusercontent.com/1803342/43998146-db17477c-9dbc-11e8-9e10-23869cd6f237.png)

```
Loading report 'D:\tmp\MyProject\output\tests\coverage\xUnit\coverage.xml'
 Preprocessing report
 Initiating parser for OpenCover
Initializing report builders for report types: Html
Analyzing 0 classes
 Creating summary
Report generation took 0.4 seconds
Sources directory not set, will try to guess. This might not work properly when merging results from multiple test assemblies.

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: str
   at System.Text.RegularExpressions.Regex.Escape(String str)
   at Palmmedia.OpenCoverToCoberturaConverter.Converter.CreateRootElement(XDocument openCoverReport, String sourcesDirectory, Boolean includeGettersSetters)
   at Palmmedia.OpenCoverToCoberturaConverter.Converter.ConvertToCobertura(XDocument openCoverReport, String sourcesDirectory, Boolean includeGettersSetters)
   at Palmmedia.OpenCoverToCoberturaConverter.Program.Main(String[] args)
```

**Comment by danielpalme** [comment]
Does the new release work for you?
https://www.nuget.org/packages/OpenCoverToCoberturaConverter/0.3.4

**Comment by asmagin** [comment]
Tried the new version. Looks like the bug is resolved.
Thanks.
